"""empty message

Revision ID: 540fda313145
Revises: 
Create Date: 2023-04-16 19:15:56.643324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540fda313145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
